using System.Text.Json.Serialization;
using PacToolkits.Application.DTOs;

namespace PacToolkits.Application.Serialization;

/// <summary>PacApi 协议 DTO 的 JsonSerializerContext</summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ChangeWatermarkItem))]
[JsonSerializable(typeof(ChangeWatermarkItem[]))]
[JsonSerializable(typeof(ChangeWatermarksResponse))]
[JsonSerializable(typeof(PacApiTokenResponse))]
[JsonSerializable(typeof(PacApiSystemInfo))]
[JsonSerializable(typeof(ClientCountDto))]
[JsonSerializable(typeof(StringListResponse))]
[JsonSerializable(typeof(DashboardSnapshotResponse))]
[JsonSerializable(typeof(DashboardKpiDto))]
[JsonSerializable(typeof(TrendRowDto))]
[JsonSerializable(typeof(TraceTxnDto))]
[JsonSerializable(typeof(TraceEntryLogDto))]
[JsonSerializable(typeof(EntryChartRowDto))]
[JsonSerializable(typeof(AbnormalRowDto))]
[JsonSerializable(typeof(PagedResult<TraceTxnDto>))]
[JsonSerializable(typeof(PagedResult<TrendRowDto>))]
[JsonSerializable(typeof(PagedResult<TraceEntryLogDto>))]
[JsonSerializable(typeof(PagedResult<AbnormalRowDto>))]
[JsonSerializable(typeof(CatalogQuantityResponse))]
[JsonSerializable(typeof(CatalogDeprecatedResponse))]
[JsonSerializable(typeof(DrugIndexDto))]
[JsonSerializable(typeof(DrugIndexSearchResult))]
[JsonSerializable(typeof(DrugIndexSaveRequest))]
[JsonSerializable(typeof(DrugIndexSaveResponse))]
[JsonSerializable(typeof(DrugSaveOutcome))]
[JsonSerializable(typeof(DrugKeyFixPreviewRequest))]
[JsonSerializable(typeof(DrugKeyFixPreviewDto))]
[JsonSerializable(typeof(DrugKeyFixRequest))]
[JsonSerializable(typeof(DrugKeyFixCommitResult))]
[JsonSerializable(typeof(DrugKeyFixApplyResultDto))]
[JsonSerializable(typeof(WriteProblemBody))]
[JsonSerializable(typeof(TraceCodesExistingRequest))]
[JsonSerializable(typeof(TraceCodesExistingResponse))]
[JsonSerializable(typeof(ScanCodeSubmitRequest))]
[JsonSerializable(typeof(ScanCodeSubmitResult))]
[JsonSerializable(typeof(ScanCodeInsertResult))]
[JsonSerializable(typeof(CodeAnalysis))]
[JsonSerializable(typeof(TraceCodeValidationRule))]
[JsonSerializable(typeof(TracePoolStockRowDto))]
[JsonSerializable(typeof(TracePoolDrugSpecAggDto))]
[JsonSerializable(typeof(LowStockRowDto))]
[JsonSerializable(typeof(MissingInventoryRowDto))]
[JsonSerializable(typeof(PagedResult<TracePoolStockRowDto>))]
[JsonSerializable(typeof(PagedResult<TracePoolDrugSpecAggDto>))]
[JsonSerializable(typeof(PagedResult<LowStockRowDto>))]
[JsonSerializable(typeof(PagedResult<MissingInventoryRowDto>))]
[JsonSerializable(typeof(InventoryStockEditRequest))]
[JsonSerializable(typeof(StockRowEditRequest))]
[JsonSerializable(typeof(StockRowEditBatchResult))]
[JsonSerializable(typeof(StockRowEditSaved))]
[JsonSerializable(typeof(StockRowEditConflict))]
[JsonSerializable(typeof(IReadOnlyList<StockRowEditConflict>))]
[JsonSerializable(typeof(InventoryStockDeleteRequest))]
[JsonSerializable(typeof(InventoryStockDeleteResponse))]
[JsonSerializable(typeof(InventoryTargetExistsResponse))]
[JsonSerializable(typeof(InventoryReassignPreviewRequest))]
[JsonSerializable(typeof(InventoryReassignCommitRequest))]
[JsonSerializable(typeof(StockReassignContext))]
[JsonSerializable(typeof(StockReassignPreviewDto))]
[JsonSerializable(typeof(StockReassignPreviewItemDto))]
[JsonSerializable(typeof(StockReassignApplyResultDto))]
public partial class PacJsonContext : JsonSerializerContext;
