<Project>
  <PropertyGroup>
    <AppVersion>1.0.2-beta.9</AppVersion>
    <Version>1.0.2-beta.9</Version>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
    <InformationalVersion>1.0.2-beta.9+beta.2026-08-19</InformationalVersion>
  </PropertyGroup>
</Project>
