<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PacToolkits.Api</RootNamespace>
    <AssemblyName>PacToolkits.Api</AssemblyName>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\packages\application\PacToolkits.Application.csproj" />
    <ProjectReference Include="..\..\..\packages\infrastructure\PacToolkits.Infrastructure.csproj" />
  </ItemGroup>

</Project>
