name: Generate Release Notes

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_release_notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Generate or update release notes
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ github.token }}
